const NFTs = [{projectName: 'Bored Ape Yacht Club', NFT: {nftNumber: '#4975', currentPrice: '50.5', nftPicture: 'https://i.seadn.io/gae/HG3ksxxOc6RzUH7KidMKwVxiyC4b7pxDsXQoa5FN4-9VznAkrIbQ8nHEdYTG1JefjNU0lLZ2ETeS7tmK5RQPRsli5qzgAZO4hs0GKrI?auto=format&w=1000', traits: [{category: 'Background', name: 'Yellow', rarity: '13%'}, {category: 'Eyes', name: 'Bored', rarity: '17%'}, {category: 'Fur', name: 'Dark Brown', rarity: '13%'}, {category: 'Hat', name:  "Girl's Hair Short", rarity: '2%'}, {category: 'Mouth', name: 'Phoneme Vuh', rarity: '3%'}]}}, 
{projectName: 'Nakamigos', NFT: {nftNumber: '#5011', nftPicture: 'https://i.seadn.io/gcs/files/02a9ffaab137213ee080f16904495893.png?auto=format&w=1000', currentPrice: '0.399', traits: [{category: 'Facial Hair', name: 'Solid Beard', rarity: '10%'}, {category: 'Hair', name: 'Shaggy', rarity: '4%'}, {category: 'Mouth', name: 'Gold', rarity: '4%'}, {category: 'Shirt/Jacket', name: 'Pajamas', rarity: '2%'}, {category: 'Type', name: 'Human Boba', rarity: '21%'}]}},
{projectName: 'Moonbirds', NFT: {nftNumber: '#8038', nftPicture: 'https://openseauserdata.com/files/034fb8d76fb7eccf6fb850f6529b1be6.bin', currentPrice: '2.65', traits: [{category: 'Background', name: 'Purple', rarity: '17%'}, {category: 'Beak', name: 'Short', rarity: '41%'}, {category: 'Body', name: 'Crescent', rarity: '35%'}, {category: 'Eyewear', name: 'Jobs Glasses', rarity: '2%'}, {category: 'Feathers', name: 'Green', rarity: '4%'}]}}, 
{projectName: 'Azuki', NFT: {nftNumber: '#604', nftPicture: 'https://i.seadn.io/gcs/files/8753d80a28bf3cec69a1bb697b22aae3.png?auto=format&w=1000', currentPrice: '15.2', traits: [{category: 'Background', name: 'Red', rarity: '10%'}, {category: 'Clothing', name: 'Shinto Robe', rarity: '1%'}, {category: 'Ear', name: 'Blue Fan', rarity: '0.69%'}, {category: 'Eyes', name: 'Closed', rarity: '16%'}, {category: 'Face', name: 'Eye Patch', rarity: '2%'}, {category: 'Hair', name: 'Teal Long', rarity: '1%'}, {category: 'Offhand', name: 'Banner', rarity: '4%'}, {category: 'Type', name: 'Human', rarity: '90%'}]}}, 
{projectName: 'Mutant Ape Yacht Club', NFT: {nftNumber: '#4207', nftPicture: 'https://i.seadn.io/gcs/files/b923e62d2e900e9fed998401e5d59b5d.png?auto=format&w=1000', currentPrice: '11.7', traits: [{category: 'Background', name: 'M1 Purple', rarity: '10%'}, {category: 'Clothes', name: 'M1 Service', rarity: '1%'}, {category: 'Eyes', name: 'M1 X Eyes', rarity: '2%'}, {category: 'Fur', name: 'M1 Cheetah', rarity: '3%'}, {category: 'Mouth', name: 'M1 Dumbfounded', rarity: '4%'}]}}, 
{projectName: 'The Captainz', NFT: {nftNumber: '#1023', nftPicture: 'https://i.seadn.io/gcs/files/f2847e3d707aad3a67e681e82744f218.gif?w=500&auto=format', currentPrice: '8.2', traits: [{category: 'Stage', name: '1', rarity: '99%'}, {category: 'Type', name: 'Human', rarity: '89%'}]}}, 
{projectName: 'DeGods', NFT: {nftNumber: '#6538', nftPicture: 'https://i.seadn.io/gcs/files/353460d79b2fad769656fb6a2d7aaefa.png?auto=format&w=1000', currentPrice: '7.98', traits: [{category: 'Background', name: 'Olive Green', rarity: '13%'}, {category: 'Clothes', name: 'Godchella Hoodie', rarity: '5%'}, {category: 'Eyes', name: 'None', rarity: '53%'}, {category: 'Head', name: 'Prince', rarity: '5%'}, {category: 'Mouth', name: 'Santa Beard', rarity: '4%'}, {category: 'Skin', name: 'Lavender Stripe', rarity: '8%'}, {category: 'Specialty', name: 'Archer', rarity: '7%'}, {category: 'Version', name: 'DeadGod', rarity: '100%'}]}}, 
{projectName: 'Invisible Friends', NFT: {nftNumber: '#3925', nftPicture: 'https://ipfs.io/ipfs/QmX4nfgA35MiW5APoc4P815hMcH8hAt7edi5H3wXkFm485/2D/3925.gif', currentPrice: '1.55', traits: [{category: 'Background', name: 'Blye', rarity: '51%'}, {category: 'Eyes', name: 'White Glasses', rarity: '8%'}, {category: 'Feet', name: 'Bubblegum Sneakers', rarity: '4%'}, {category: 'Left Arm', name: 'Swinging', rarity: '49%'}, {category: 'Legs', name: 'Red Sweatpants', rarity: '4%'}, {category: 'Right Arm', name: 'Dog', rarity: '3%'}, {category: 'Sleeves', name: 'Long Sleeves', rarity: '89%'}]}}, 
{projectName: 'a Kid called BEAST', NFT: {nftNumber: '#5597', nftPicture: 'https://i.seadn.io/gcs/files/a8663b1acfd825bb69919e7f3fd55e52.png?auto=format&w=384', currentPrice: '0.45', traits: [{category: 'Balaclava', name: 'Hyena', rarity: '4%'}, {category: 'BeastHood', name: 'Concrete Jungle', rarity: '5%'}, {category: 'Pants', name: 'Chestnut', rarity: '4%'}, {category: 'Denim Vest', name: 'Washed Denim', rarity: '0.18%'}, {category: 'DNA', name: 'Human', rarity: '97%'}, {category: 'Eyes', name: 'Human Pupils', rarity: '85%'}, {category: 'Footwear', name: 'Hiking Boots', rarity: '3%'}]}},
{projectName: 'CryptoPunks V1 (wrapped)', NFT: {nftNumber: '#4610', nftPicture: 'https://i.seadn.io/gcs/files/8e97e6c38db13d64043cc7be5314daeb.png?auto=format&w=1000', currentPrice: '4.55', traits: [{category: 'Background', name: 'Purple', rarity: '13%'}, {category: 'Body', name: 'Male', rarity: '64%'}, {category: 'Earring', name: 'Yes', rarity: '27%'}, {category: 'Eyes', name: 'Eye Mask', rarity: '3%'}, {category: 'Hair', name: 'Stringy Hair', rarity: '6%'}]}}]

export default NFTs;

// {projectName: '', NFT: {nftNumber: '#4975', nftPicture: '', currentPrice: '', traits: [{category: 'Background', name: 'Yellow', rarity: '13%'}]}}

// , {category: 'Type', name: 'Human', rarity: '89%'}